services:
  db:
    image: postgres:15
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env # <--- Docker leerá las credenciales de aquí
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env # <--- Django también las leerá
    depends_on:
      db:
        condition: service_started
      sqlserver:
        condition: service_started

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - "1433:1433"
    volumes:
      - ./DB:/var/opt/mssql/scripts
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 10
      start_period: 45s

  db-init:
    build: ./DB
    depends_on:
      sqlserver:
        condition: service_healthy
    env_file:
      - .env
    command: >
      /bin/bash -c " echo 'Waiting for SQL Server to be ready...'; sleep 15; echo 'Initializing Databases...'; /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P $MSSQL_SA_PASSWORD -C -i /var/opt/mssql/scripts/00_init_databases.sql; echo 'Running SIGH.sql...'; /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P $MSSQL_SA_PASSWORD -C -i /var/opt/mssql/scripts/SIGH.sql; echo 'Running SIGH_EXTERNA.sql...'; /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P $MSSQL_SA_PASSWORD -C -i /var/opt/mssql/scripts/SIGH_EXTERNA.sql; echo 'Running SIGH_SIS.sql...'; /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P $MSSQL_SA_PASSWORD -C -i /var/opt/mssql/scripts/SIGH_SIS.sql; echo 'Running BDHIS_MINSA.sql...'; /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P $MSSQL_SA_PASSWORD -C -i /var/opt/mssql/scripts/BDHIS_MINSA.sql; echo 'Database initialization completed.'; "
