# Generated by Django 5.0.1 on 2026-01-19 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='fas fa-folder', help_text='Clase FontAwesome, ej: fas fa-chart-line', max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('sp_ejecutado', models.CharField(max_length=255)),
                ('parametros', models.TextField()),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MSSQLServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador del servidor', max_length=100)),
                ('host', models.CharField(help_text='IP o Hostname del servidor SQL', max_length=255)),
                ('database', models.CharField(help_text='Base de datos por defecto', max_length=100)),
                ('usuario', models.CharField(help_text='Usuario SQL', max_length=100)),
                ('password_encrypted', models.CharField(blank=True, help_text='Contraseña encriptada', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sp_nombre', models.CharField(help_text='Nombre del Stored Procedure en SQL Server', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.categoriareporte')),
            ],
        ),
    ]
